{% set name = "csvlens" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/YS-L/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d653c97c55c8638d2137dfc3b8dcb62f6d76a6786eadc468086e23214cbea3c4

build:
  number: 0

requirements:
  build:
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - csvlens --version

about:
  home: https://github.com/YS-L/csvlens
  dev_url: https://github.com/YS-L/csvlens
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  summary: A command line csv viewer

extra:
  recipe-maintainers:
    - apcamargo
