{% set name = "csvlens" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/YS-L/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4396cf4e0c51be589f86aed662b9cb03f4f9414d8e2fd80dbc18f20eaf447bb7

build:
  number: 0

requirements:
  build:
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - csvlens --version

about:
  home: https://github.com/YS-L/csvlens
  dev_url: https://github.com/YS-L/csvlens
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  summary: A command line csv viewer

extra:
  recipe-maintainers:
    - apcamargo
