{% set name = "csvlens" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/YS-L/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d95a3029e4ec471feb337f465e36910f712c790e629c8b23357d00b705399f6d

build:
  number: 0

requirements:
  build:
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - csvlens --version

about:
  home: https://github.com/YS-L/csvlens
  dev_url: https://github.com/YS-L/csvlens
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  summary: A command line csv viewer

extra:
  recipe-maintainers:
    - apcamargo
